apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-producer-rose
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: data-producer
      environment: rose
  template:
    metadata:
      labels:
        app: data-producer
        environment: rose
    spec:
      containers:
      - name: data-producer
        image: larutyunov/data-producer:2
        ports:
        - containerPort: 8080
        env:
        - name: CONSUMER.URL
          value: "http://data-consumer:8080"